### ISSUE TITLE
Item Frame Server Error

### ISSUE THREAD

**Issue by WenXin20** [GiantLuigi4/dynamic-weapons#7]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Dynamic Weaponry Beta v2`

After trying to place a dynamic weapon in an item frame, I got disconnected from my server:

```
01.02 14:28:39 [Server] Netty Epoll Server IO #3/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
01.02 14:28:39 [Disconnect] User WenXin2 has disconnected, reason: Internal Exception: java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
01.02 14:28:39 [Server] Server thread/INFO [minecraft/DedicatedServer]: WenXin2 left the game
```

![2021-02-01_13 30 00](https://user-images.githubusercontent.com/12000593/106508381-f34edf00-6491-11eb-8595-6e709182d922.png)

**Comment by GiantLuigi4** [comment]
This issue actually isn't related to dynamic weaponry, it's related to the mod which it depends on (Assorted Utils).

try this jar for assorted utils:
[AssortedUtils.zip](https://github.com/GiantLuigi4/dynamic-weapons/files/5906335/AssortedUtils.zip)

(jar is zipped inside, so do make sure you take the jar out of the zip instead of just putting the zip in)

(this disconnect will happen if you attack or click any entity)

**Comment by WenXin20** [comment]
Alright, thanks

**Comment by GiantLuigi4** [comment]
Reason I was able to point you to the actual culprit so quickly is because I have a server which has the mod (hosted by a user called LorenzoPapi) linked to my discord server, and at the start of the server, me and a different user Mohatax (who made Shulkered), were unable to get food because of this, as we couldn't kill pigs nor fish to get food, and clicking on any entity through either click would dc us
